// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// tests the event editing UI
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlInputButton uILogintocontinueButton = this.UIHomePageTrailMixInteWindow.UIHomePageTrailMixDocument.UILogintocontinueButton;
            HtmlEdit uIUsernameEdit = this.UIHomePageTrailMixInteWindow.UILoginTrailMixDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIHomePageTrailMixInteWindow.UILoginTrailMixDocument.UIPasswordEdit;
            HtmlInputButton uILoginButton = this.UIHomePageTrailMixInteWindow.UILoginTrailMixDocument.UILoginFormCustom.UILoginButton;
            HtmlHyperlink uIManageEventsHyperlink = this.UIHomePageTrailMixInteWindow.UIHomePageTrailMixDocument.UIManageEventsHyperlink;
            HtmlHyperlink uIEditHyperlink = this.UIHomePageTrailMixInteWindow.UIEventsTrailMixDocument.UIEditHyperlink;
            HtmlDiv uIItemPane = this.UIHomePageTrailMixInteWindow.UIEditTrailMixDocument.UIItemPane;
            HtmlEdit uIEventLocationEdit = this.UIHomePageTrailMixInteWindow.UIEditTrailMixDocument.UIEventLocationEdit;
            HtmlInputButton uISaveButton = this.UIHomePageTrailMixInteWindow.UIEditTrailMixDocument.UISaveButton;
            #endregion

            // Click 'Login to continue' button
            Mouse.Click(uILogintocontinueButton, new Point(177, 36));

            // Type 'admin' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod1Params.UIUsernameEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod1Params.UIPasswordEditPassword;

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(95, 27));

            // Click 'Manage Events' link
            Mouse.Click(uIManageEventsHyperlink, new Point(255, 43));

            // Click 'Edit' link
            Mouse.Click(uIEditHyperlink, new Point(9, 14));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Type 'Mississauga' in 'eventLocation' text box
            uIEventLocationEdit.Text = this.RecordedMethod1Params.UIEventLocationEditText;

            // Type 'Mississauga1' in 'eventLocation' text box
            uIEventLocationEdit.Text = this.RecordedMethod1Params.UIEventLocationEditText1;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(86, 33));
        }
        
        /// <summary>
        /// edit event testing
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            HtmlInputButton uILogintocontinueButton = this.UIHomePageTrailMixInteWindow.UIHomePageTrailMixDocument.UILogintocontinueButton;
            HtmlEdit uIUsernameEdit = this.UIHomePageTrailMixInteWindow.UILoginTrailMixDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIHomePageTrailMixInteWindow.UILoginTrailMixDocument.UIPasswordEdit;
            HtmlInputButton uILoginButton = this.UIHomePageTrailMixInteWindow.UILoginTrailMixDocument.UILoginFormCustom.UILoginButton;
            HtmlHyperlink uIManageEventsHyperlink = this.UIHomePageTrailMixInteWindow.UIHomePageTrailMixDocument.UIManageEventsHyperlink;
            HtmlHyperlink uIEditHyperlink = this.UIHomePageTrailMixInteWindow.UIEventsTrailMixDocument.UIEditHyperlink;
            HtmlDiv uIItemPane = this.UIHomePageTrailMixInteWindow.UIEditTrailMixDocument.UIItemPane;
            HtmlEdit uIEventLocationEdit = this.UIHomePageTrailMixInteWindow.UIEditTrailMixDocument.UIEventLocationEdit;
            HtmlInputButton uISaveButton = this.UIHomePageTrailMixInteWindow.UIEditTrailMixDocument.UISaveButton;
            #endregion

            // Click 'Login to continue' button
            Mouse.Click(uILogintocontinueButton, new Point(177, 36));

            // Type 'admin' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod2Params.UIUsernameEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod2Params.UIPasswordEditPassword;

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(95, 27));

            // Click 'Manage Events' link
            Mouse.Click(uIManageEventsHyperlink, new Point(255, 43));

            // Click 'Edit' link
            Mouse.Click(uIEditHyperlink, new Point(9, 14));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Type 'Mississauga' in 'eventLocation' text box
            uIEventLocationEdit.Text = this.RecordedMethod2Params.UIEventLocationEditText;

            // Type 'Mississauga1' in 'eventLocation' text box
            uIEventLocationEdit.Text = this.RecordedMethod2Params.UIEventLocationEditText1;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(86, 33));

            // Click 'Login to continue' button
            Mouse.Click(uILogintocontinueButton, new Point(145, 27));

            // Type 'admin' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod2Params.UIUsernameEditText1;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit, this.RecordedMethod2Params.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod2Params.UIPasswordEditPassword1;

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(47, 52));

            // Click 'Manage Events' link
            Mouse.Click(uIManageEventsHyperlink, new Point(311, 47));

            // Click 'Edit' link
            Mouse.Click(uIEditHyperlink, new Point(14, 12));

            // Type 'Mississauga' in 'eventLocation' text box
            uIEventLocationEdit.Text = this.RecordedMethod2Params.UIEventLocationEditText2;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(35, 25));
        }
        
        /// <summary>
        /// tests ecent editing UI
        /// </summary>
        public void editEventTest()
        {
            #region Variable Declarations
            HtmlInputButton uILogintocontinueButton = this.UIHomePageTrailMixInteWindow.UIHomePageTrailMixDocument.UILogintocontinueButton;
            HtmlEdit uIUsernameEdit = this.UIHomePageTrailMixInteWindow.UILoginTrailMixDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIHomePageTrailMixInteWindow.UILoginTrailMixDocument.UIPasswordEdit;
            HtmlInputButton uILoginButton = this.UIHomePageTrailMixInteWindow.UILoginTrailMixDocument.UILoginFormCustom.UILoginButton;
            HtmlHyperlink uIManageEventsHyperlink = this.UIHomePageTrailMixInteWindow.UIHomePageTrailMixDocument.UIManageEventsHyperlink;
            HtmlHyperlink uIEditHyperlink = this.UIHomePageTrailMixInteWindow.UIEventsTrailMixDocument.UIEditHyperlink;
            HtmlEdit uIEventLocationEdit = this.UIHomePageTrailMixInteWindow.UIEditTrailMixDocument.UIEventLocationEdit;
            HtmlInputButton uISaveButton = this.UIHomePageTrailMixInteWindow.UIEditTrailMixDocument.UISaveButton;
            HtmlCell uIMississauga12Cell = this.UIHomePageTrailMixInteWindow.UIEventsTrailMixDocument.UIItemTable.UIMississauga12Cell;
            #endregion

            // Click 'Login to continue' button
            Mouse.Click(uILogintocontinueButton, new Point(274, 53));

            // Type 'admin' in 'User name' text box
            uIUsernameEdit.Text = this.editEventTestParams.UIUsernameEditText;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit, this.editEventTestParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.editEventTestParams.UIPasswordEditPassword;

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(23, 57));

            // Click 'Manage Events' link
            Mouse.Click(uIManageEventsHyperlink, new Point(313, 33));

            // Click 'Edit' link
            Mouse.Click(uIEditHyperlink, new Point(3, 13));

            // Type 'Mississauga12' in 'eventLocation' text box
            uIEventLocationEdit.Text = this.editEventTestParams.UIEventLocationEditText;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(79, 11));

            // Click 'Mississauga12' cell
            Mouse.Click(uIMississauga12Cell, new Point(79, 40));
        }
        
        /// <summary>
        /// AssertMethod1 - Use 'AssertMethod1ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            HtmlCell uIMississauga12Cell = this.UIHomePageTrailMixInteWindow.UIEventsTrailMixDocument.UIItemTable.UIMississauga12Cell;
            #endregion

            // Verify that the 'InnerText' property of 'Mississauga12' cell equals 'Mississauga12 '
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIMississauga12CellInnerText, uIMississauga12Cell.InnerText, "Event Editing Test Fails");
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public virtual editEventTestParams editEventTestParams
        {
            get
            {
                if ((this.meditEventTestParams == null))
                {
                    this.meditEventTestParams = new editEventTestParams();
                }
                return this.meditEventTestParams;
            }
        }
        
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public UIHomePageTrailMixInteWindow UIHomePageTrailMixInteWindow
        {
            get
            {
                if ((this.mUIHomePageTrailMixInteWindow == null))
                {
                    this.mUIHomePageTrailMixInteWindow = new UIHomePageTrailMixInteWindow();
                }
                return this.mUIHomePageTrailMixInteWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private editEventTestParams meditEventTestParams;
        
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private UIHomePageTrailMixInteWindow mUIHomePageTrailMixInteWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "S6BpkXC7RCrSFRA87Cpgpu0Ip1x6w5nX";
        
        /// <summary>
        /// Type 'Mississauga' in 'eventLocation' text box
        /// </summary>
        public string UIEventLocationEditText = "Mississauga";
        
        /// <summary>
        /// Type 'Mississauga1' in 'eventLocation' text box
        /// </summary>
        public string UIEventLocationEditText1 = "Mississauga1";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "S6BpkXC7RCrSFRA87Cpgpu0Ip1x6w5nX";
        
        /// <summary>
        /// Type 'Mississauga' in 'eventLocation' text box
        /// </summary>
        public string UIEventLocationEditText = "Mississauga";
        
        /// <summary>
        /// Type 'Mississauga1' in 'eventLocation' text box
        /// </summary>
        public string UIEventLocationEditText1 = "Mississauga1";
        
        /// <summary>
        /// Type 'admin' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText1 = "admin";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword1 = "S6BpkXC7RCrSFRA87Cpgpu0Ip1x6w5nX";
        
        /// <summary>
        /// Type 'Mississauga' in 'eventLocation' text box
        /// </summary>
        public string UIEventLocationEditText2 = "Mississauga";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'editEventTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class editEventTestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "admin";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "S6BpkXC7RCrSFRA87Cpgpu0Ip1x6w5nX";
        
        /// <summary>
        /// Type 'Mississauga12' in 'eventLocation' text box
        /// </summary>
        public string UIEventLocationEditText = "Mississauga12";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Mississauga12' cell equals 'Mississauga12 '
        /// </summary>
        public string UIMississauga12CellInnerText = "Mississauga12 ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHomePageTrailMixInteWindow : BrowserWindow
    {
        
        public UIHomePageTrailMixInteWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page - TrailMix";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page - TrailMix");
            this.WindowTitles.Add("Log in - TrailMix");
            this.WindowTitles.Add("Events - TrailMix");
            this.WindowTitles.Add("Edit - TrailMix");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageTrailMixDocument UIHomePageTrailMixDocument
        {
            get
            {
                if ((this.mUIHomePageTrailMixDocument == null))
                {
                    this.mUIHomePageTrailMixDocument = new UIHomePageTrailMixDocument(this);
                }
                return this.mUIHomePageTrailMixDocument;
            }
        }
        
        public UILoginTrailMixDocument UILoginTrailMixDocument
        {
            get
            {
                if ((this.mUILoginTrailMixDocument == null))
                {
                    this.mUILoginTrailMixDocument = new UILoginTrailMixDocument(this);
                }
                return this.mUILoginTrailMixDocument;
            }
        }
        
        public UIEventsTrailMixDocument UIEventsTrailMixDocument
        {
            get
            {
                if ((this.mUIEventsTrailMixDocument == null))
                {
                    this.mUIEventsTrailMixDocument = new UIEventsTrailMixDocument(this);
                }
                return this.mUIEventsTrailMixDocument;
            }
        }
        
        public UIEditTrailMixDocument UIEditTrailMixDocument
        {
            get
            {
                if ((this.mUIEditTrailMixDocument == null))
                {
                    this.mUIEditTrailMixDocument = new UIEditTrailMixDocument(this);
                }
                return this.mUIEditTrailMixDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageTrailMixDocument mUIHomePageTrailMixDocument;
        
        private UILoginTrailMixDocument mUILoginTrailMixDocument;
        
        private UIEventsTrailMixDocument mUIEventsTrailMixDocument;
        
        private UIEditTrailMixDocument mUIEditTrailMixDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHomePageTrailMixDocument : HtmlDocument
    {
        
        public UIHomePageTrailMixDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - TrailMix";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:1471/";
            this.WindowTitles.Add("Home Page - TrailMix");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UILogintocontinueButton
        {
            get
            {
                if ((this.mUILogintocontinueButton == null))
                {
                    this.mUILogintocontinueButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILogintocontinueButton.SearchProperties[HtmlButton.PropertyNames.Id] = "loginLink";
                    this.mUILogintocontinueButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILogintocontinueButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Login to continue";
                    this.mUILogintocontinueButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUILogintocontinueButton.FilterProperties[HtmlButton.PropertyNames.Title] = "Login to continue";
                    this.mUILogintocontinueButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-lg btn-success";
                    this.mUILogintocontinueButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "title=\"Login to continue\" class=\"btn btn";
                    this.mUILogintocontinueButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUILogintocontinueButton.WindowTitles.Add("Home Page - TrailMix");
                    #endregion
                }
                return this.mUILogintocontinueButton;
            }
        }
        
        public HtmlHyperlink UIManageEventsHyperlink
        {
            get
            {
                if ((this.mUIManageEventsHyperlink == null))
                {
                    this.mUIManageEventsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIManageEventsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIManageEventsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIManageEventsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIManageEventsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Manage Events";
                    this.mUIManageEventsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Event";
                    this.mUIManageEventsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIManageEventsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:1471/Event";
                    this.mUIManageEventsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIManageEventsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Event\"";
                    this.mUIManageEventsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUIManageEventsHyperlink.WindowTitles.Add("Home Page - TrailMix");
                    #endregion
                }
                return this.mUIManageEventsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUILogintocontinueButton;
        
        private HtmlHyperlink mUIManageEventsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UILoginTrailMixDocument : HtmlDocument
    {
        
        public UILoginTrailMixDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Log in - TrailMix";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:1471/Account/Login";
            this.WindowTitles.Add("Log in - TrailMix");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "UserName";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "UserName";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User name";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"UserName\" class=\"form-control\" id=";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIUsernameEdit.WindowTitles.Add("Log in - TrailMix");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswordEdit.WindowTitles.Add("Log in - TrailMix");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public UILoginFormCustom UILoginFormCustom
        {
            get
            {
                if ((this.mUILoginFormCustom == null))
                {
                    this.mUILoginFormCustom = new UILoginFormCustom(this);
                }
                return this.mUILoginFormCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private UILoginFormCustom mUILoginFormCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UILoginFormCustom : HtmlCustom
    {
        
        public UILoginFormCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "SECTION";
            this.SearchProperties["Id"] = "loginForm";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"loginForm\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Log in - TrailMix");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Log in";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" type=\"submit\" va";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUILoginButton.WindowTitles.Add("Log in - TrailMix");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIEventsTrailMixDocument : HtmlDocument
    {
        
        public UIEventsTrailMixDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Events - TrailMix";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Event";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:1471/Event";
            this.WindowTitles.Add("Events - TrailMix");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIEditHyperlink
        {
            get
            {
                if ((this.mUIEditHyperlink == null))
                {
                    this.mUIEditHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Edit";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Event/Edit/1";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:1471/Event/Edit/1";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Event/Edit/1\"";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "10";
                    this.mUIEditHyperlink.WindowTitles.Add("Events - TrailMix");
                    #endregion
                }
                return this.mUIEditHyperlink;
            }
        }
        
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIEditHyperlink;
        
        private UIItemTable mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Event \r\n\r\nLocation \r\n\r\nEventInfo \r\n\r\nTim";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "5";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Events - TrailMix");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIMississauga12Cell
        {
            get
            {
                if ((this.mUIMississauga12Cell == null))
                {
                    this.mUIMississauga12Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIMississauga12Cell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIMississauga12Cell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIMississauga12Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIMississauga12Cell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Mississauga12 ";
                    this.mUIMississauga12Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIMississauga12Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIMississauga12Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUIMississauga12Cell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIMississauga12Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "2";
                    this.mUIMississauga12Cell.WindowTitles.Add("Events - TrailMix");
                    #endregion
                }
                return this.mUIMississauga12Cell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIMississauga12Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIEditTrailMixDocument : HtmlDocument
    {
        
        public UIEditTrailMixDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Edit - TrailMix";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Event/Edit/1";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:1471/Event/Edit/1";
            this.WindowTitles.Add("Edit - TrailMix");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "col-md-10";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"col-md-10\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "10";
                    this.mUIItemPane.WindowTitles.Add("Edit - TrailMix");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public HtmlEdit UIEventLocationEdit
        {
            get
            {
                if ((this.mUIEventLocationEdit == null))
                {
                    this.mUIEventLocationEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEventLocationEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "eventLocation";
                    this.mUIEventLocationEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "eventLocation";
                    this.mUIEventLocationEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "eventLocation";
                    this.mUIEventLocationEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEventLocationEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEventLocationEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "text-box single-line";
                    this.mUIEventLocationEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"eventLocation\" class=\"text-box sin";
                    this.mUIEventLocationEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIEventLocationEdit.WindowTitles.Add("Edit - TrailMix");
                    #endregion
                }
                return this.mUIEventLocationEdit;
            }
        }
        
        public HtmlInputButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Save";
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "8";
                    this.mUISaveButton.WindowTitles.Add("Edit - TrailMix");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        
        private HtmlEdit mUIEventLocationEdit;
        
        private HtmlInputButton mUISaveButton;
        #endregion
    }
}
