//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrailUsage
    {
        public int Id { get; set; }
        public System.DateTime trailAccessDate { get; set; }
        public int Trail_Id { get; set; }
        public string activity { get; set; }
    
        public virtual Trail Trail { get; set; }
    }
}
