//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrailAccessPoint
    {
        public int Id { get; set; }
        public double longitude { get; set; }
        public double lattitude { get; set; }
        public string locationName { get; set; }
        public int TrailId { get; set; }
        public int City_Id { get; set; }
    
        public virtual City City { get; set; }
        public virtual Trail Trail { get; set; }
    }
}
